version: "3.8"
services:
  app:
    build: fpm
    working_dir: /app
    volumes:
      - ../:/app
      - ../storage/app/public:/app/public/storage
    ports:
      - "2222:22"

  web:
    image: nginx:1-alpine
    volumes:
      - ../:/usr/share/nginx/html:ro
      - ../storage/app/public:/usr/share/nginx/html/public/storage:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - 80:80
    depends_on:
      - app

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gitservice
    volumes:
      - gitservice_db_data:/var/lib/mysql
      - ../:/app
  
  # testdb:
  #   image: mysql:5.7
  #   tmpfs: /var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=gitservice_testing

volumes:
  gitservice_db_data:
